### ISSUE TITLE
"Proceedings journals" is ambiguous AF

### ISSUE THREAD

**Issue by rossmounce** [ropensci/suppdata#12]
Reading suppdata.R I had literally no clue which "Proceedings journals" you're talking about.

The following are all "Proceedings journals" in terms of journal title:
* PNAS http://www.pnas.org/
* Proceedings of the Academy of Natural Sciences of Philadelphia  http://www.bioone.org/toc/ansp/current
* Proceedings of the Biological Society of Washington http://www.bioone.org/toc/pbsw/current
* Proceedings of the Entomological Society of Washington http://www.bioone.org/loi/went  
* Proceedings of the Institution of Mechanical Engineers, Part C: Journal of Mechanical Engineering Science https://uk.sagepub.com/en-gb/eur/proceedings-of-the-institution-of-mechanical-engineers-part-c-journal-of-mechanical-engineering 
* et cetera ad nauseum

Only by then examining journals.R and seeing "royalsocietypublishing.org/content" do I infer you mean Royal Society Publishing journals(?)
 
Furthermore, not all Royal Society Publishing journals even have 'proceedings' in their names. If you do mean Royal Society Publishing journals and the code works across all Royal Society Publishing journals (as I imagine it would, but untested!), then perhaps say Royal Society Publishing journals and use a less ambiguous shorthand reference other than "proceedings"?

**Comment by willpearse** [comment]
This is described further down in the table within the help file: https://github.com/willpearse/suppdata/blob/master/man/suppdata.Rd#L119
