### ISSUE TITLE
Make community contributions for specific publisher-platforms easier

### ISSUE THREAD

**Issue by rossmounce** [ropensci/suppdata#18]
I'm involved with the ContentMine community. We've built journal scrapers before, including supplementary data as an element of the overall scrape. As a process it doesn't scale very well:

a) There is a very long tail of publishers - significant diversity
b) Publisher platforms (the precise access mechanisms) and URLs, change over time (a maintenance burden)

At ContentMine we managed to support scrapers for about 30 different publisher platforms:
https://github.com/ContentMine/journal-scrapers/tree/master/scrapers 

But this diversity was only achieved through community contribution, workshops, and dialogue into user interests -- finding out the journals they needed stuff from.

I love this R package. It's great that there's going to be standardised tools for suppdata scraping in R. 

(I may be thinking too many steps ahead here, I appreciate you just want to get the basic minimal package out first, but...) I do think you need to put some thought into providing _rich_ documentation on how external contributors can contribute specific suppdata scrapers for publisher platforms they are interested in.

These are deeply imperfect examples, but for reference this is how ContentMine tried to do this:
https://github.com/ContentMine/workshop-resources/tree/master/software-tutorials/journal-scrapers 
http://rossmounce.co.uk/2015/05/13/making-a-journal-scraper/

It might also help structurally if you refactored the code, so that community contributions of publisher-platform specific suppdata download methods can be added as atomic, separate files (c.f. ContentMine's scraper .json files) that are called from the main `suppdata` codebase. Yes, that's a small added layer of complication but in the longer-term given the diversity of the problem I think that's a healthy idea, no? 

As a further example of the kind of documentation required, Ethan White's Open Grants project is exactly the kind of thing I think is needed here. Clear documentation on how to contribute, and contributions can be made as atomic files or via GH issues: https://github.com/weecology/ogrants 

I would love to contribute some further scrapers myself. I know the suppdata ecosystem well, I know regular expressions, I'm just not that good at R. Make it easier for people like me?

**Comment by willpearse** [comment]
Thanks for this; I've responded to this in some detail in the 'response to reviewers', but the TL;DR would be that I've added some detailed instructions for contributors, which hopefully should make things easier.
