### ISSUE TITLE
Add support for PeerJ and PeerJ Preprints

### ISSUE THREAD

**Issue by nuest** [ropensci/suppdata#25]
Extending #2, this issue is about adding support for [PeerJ](http://peerj.com/) and [PeerJ Preprints](https://peerj.com/preprints/)

Starting with searches for "rstats" and the [most cited papers in 2017](https://peerj.com/blog/post/115284879975/peerj-in-2017/), the following test dataset is used:

- https://peerj.com/articles/3006/#supplemental-information with DOI `10.7717/peerj.3006`
- https://peerj.com/preprints/26561/#supplementary-material with DOI `10.7287/peerj.preprints.26561v1`

Publisher codes are the same for both journals (the prefixes differ):

```
> cr_works(dois = "10.7717/peerj.3006")$data$member
[1] "4443"
> cr_works(dois = "10.7287/peerj.preprints.26561v1")$data$member
[1] "4443"
```

The code should download the articles XML metadata to detect the full download URLs.

**Comment by willpearse** [comment]
Can I close this? It seems as though you've done this, no?
