### ISSUE TITLE
install instructions and cran

### ISSUE THREAD

**Issue by sckott** [ropensci/suppdata#31]
@willpearse can you update the readme? it has install instructions for the wrong github user name https://github.com/ropensci/suppdata#how-to-install-and-load-this-development-version 

also, do you plan to submit to CRAN soon?  It'd be helpful for me so that I can remove the functionality from `fulltext`

**Comment by willpearse** [comment]
I will try and submit to CRAN at the end of this week. I held off because I couldn't get it to reliably pass tests on CRAN's checking server (it checks so many times so quickly that I think it was getting 408 errors or the like. I can just drop them from the CRAN tests and we should be fine.

**Comment by willpearse** [comment]
...I've fixed this now, but I will leave this issue until I submit

**Comment by sckott** [comment]
thanks.

**Comment by nuest** [comment]
@willpearse Anything I can do to help?

**Comment by willpearse** [comment]
If you have the time (and I emphasise, only if you have the time!) moving
some of the tests so they don't check "on cran" would be helpful. That's
what's been giving me grief and slowing me uploading it to CRAN (that and
I'm travelling this week and next).

If you don't have time, don't worry about it. Thanks for your help, Daniel!
Yet another beer owed!!!

**Comment by nuest** [comment]
I realise now that I cannot replicate the problem that you probably got after you submitted to CRAN.
_Can you forward the email from CRAN if you have one?_

Here's what I did in #34

- seperate tests to one file per publisher and one `test_that` per feature

This should allow us to have an easier grasp of non-essential tests for each publisher/feature that we can skip.

Tests work locally without issues (`R CMD check --as-cran`) and also using

```
rhub::check_with_rdevel(email = "...") # need email because not maintainer
rhub::check_for_cran(email = "...")
```

Results:

- https://builder.r-hub.io/status/suppdata_1.0.0.9004.tar.gz-ed4e931c1b384f499ace318f9ce140e7 (rdevel)
- https://builder.r-hub.io/status/suppdata_1.0.0.9004.tar.gz-9e3ae1af382b4224bc65083d8469f169  (for CRAN)

On my machine, I can see a difference in running all test vs. "on CRAN" (~ 170s rep. 110s), as I reduced the number of tests for each service to 1 (sometimes 2).

**Comment by sckott** [comment]
Any updates on this?  Anything I can do to help get this to CRAN?

**Comment by willpearse** [comment]
Uploaded to CRAN! Fingers crossed all goes smoothly! Thank you both for your help!!!
:fireworks:

**Comment by nuest** [comment]
@willpearse https://cran.r-project.org/web/packages/suppdata - the package does not seem to be on CRAN... have you received any replies?

**Comment by willpearse** [comment]
No, so I resubmitted, and then all seemed well, except... The problem I warned about with the unit tests sometimes failing (...because of too many requests as different versions are tested on the same server, I imagine) came up. The package then didn't even get through to the stage of being checked by a human.

I realise you suggested we could use mocking to get the tests to run #36 , but I think the best solution is to wrap most of the tests in a "not CRAN" block and just get this up there. I'm going to merge your new fantastic code (thank you!!!) into the master branch, wrap the tests appropriately, and then we can try our luck again.

**Comment by willpearse** [comment]
An update: one of the tests that previously was passing was now failing (see https://github.com/ropensci/suppdata/commit/1bcd9dad487038d83db910fe9efe30869462c1f7), but fixing this doesn't resolve the problem above. _Some_ of the CRAN tests were failing, but not all: this is still the server time-out issue I mentioned.
