### ISSUE TITLE
(Mozilla) Sprint 2019 planning

### ISSUE THREAD

**Issue by willpearse** [ropensci/suppdata#35]
Here's a thread/issue to keep track of our planning for the Mozilla Code Sprint 2019. I've put some vague to-do items below; feel free to add @nuest 

- [ ] Finalise date
- [ ] Confirm Mozilla are running it this year (if not, let's do one ourselves)
- [ ] Make it easy to temporarily claim a journal/function to work on (to avoid inter-continental code duplication :p)
- [ ] Check through 'how to get started' resources (likely through Will's Bio Nerd Herd)
- [ ] Co-ordinate timings etc. between Berlin, Utah, and Philadelphia
- [x] Get Daniel on the Nerd Herd slack channel

**Comment by nuest** [comment]
To participate in the Mozilla global Sprint, here's a few things for us to do **before**

- [ ] register individually to be part of the big event: https://foundation.mozilla.org/en/opportunity/global-sprint/register/
- [ ] **tag issues on the `suppdata` repository** suitable for sprinters (and split up the existing journal ideas to seperate issues, see #2)
- [ ] register as a project, via link on https://foundation.mozilla.org/en/opportunity/global-sprint/lead-project/
- [ ] share participation guidelines with the groups we have involved offline: https://mozilla.github.io/global-sprint/participants-guide/
- [ ] @willpearse and @nuest prepare by reading the project lead guide: https://mozilla.github.io/global-sprint/project-lead-guide/
- [x] make sure to meet both minimum project requirements and _featured project_ requirements from https://mozilla.github.io/global-sprint/project-lead-guide/project-requirements/
  - minimal
    - [x] GitHub repo
    - [x] license
    - [x] README
    - [x] issue tracker
  - featured
    - [x] contributor guidelines
    - [x] CoC
- [ ] register as a featured project, see https://mozilla.github.io/global-sprint/project-lead-guide/featured-projects/

**During the sprint**

- [ ] add information regularly to the issue in the Global Sprint repository (see [example](https://github.com/mozilla/global-sprint/issues/317))
- [ ] collaboratively take notes and interact with outside contributors via an Etherpad: **https://public.etherpad-mozilla.org/p/global-sprint-2019-suppdata**

**Comment by nuest** [comment]
@willpearse I fail to find any updated information for a 2019 sprint. Maybe the page with the concrete date was wrong? The original source for the date was https://medium.com/read-write-participate/local-leads-wanted-gather-and-grow-your-local-community-at-mozillas-2019-global-sprint-march-938481c48a37 and also this tweet: https://twitter.com/MozillaScience/status/1064509598403567616

**Comment by nuest** [comment]
Let's see if we can get an answer: https://twitter.com/nordholmen/status/1110124190013771777

**Comment by willpearse** [comment]
...and the answer was it's not a "day" this year, but rather a month. So, in a private thread, @nuest and I decided to push ahead with @nuest 's previous idea of having 'a function a month' type coding
