### ISSUE TITLE
Data download via DOI from data repository

### ISSUE THREAD

**Issue by nuest** [ropensci/suppdata#37]
For future references (and to add some search terms) and to discuss the scope of this package: This package is specifically for downloading data based on an _article's DOI_, not for DOIs given to a dataset itself.

Data should be published in data repositories such as Zenodo, Figshare, b2share, ... see re3data.org for a long list. Other packages should/could handle that, see e.g. https://github.com/ropenscilabs/doidata (concept only so far).

@willpearse What is your take on this? I initiatlly thought "maybe we should add support for Zenodo to this package?" and then recalled the `doidata` idea.

**Comment by willpearse** [comment]
I have three grants due at the end of this week, so forgive me if I'm a little terse below! :p

We support Figshare already, and I think I was asked to pull `suppdata` out of `fulltext` _after_ Noam defined the `doidata` intention. @noamross should probably chime in, but I don't really see why (given we've already started doing some of this) we couldn't continue and prioritise adding in things like Zenodo at our upcoming hack-a-thon. What do you think, Noam?

**Comment by willpearse** [comment]
Because we haven't heard back from this, I'm going to assume that my answer (that we already, to some extent, do this in this package, and that we should continue to do so) is sufficient. Marking as closed, but happy to re-open if someone disagrees or if this crops up again in conversation.
