### ISSUE TITLE
Add support for JStatSoft

### ISSUE THREAD

**Issue by nuest** [ropensci/suppdata#42]
Potentially add a layer that makes it easy to add other []()-based journals.

Journal: https://www.jstatsoft.org/

Example articles (any article has at least the code as supplementary data):

- https://www.jstatsoft.org/article/view/v088i05 and https://www.jstatsoft.org/article/view/v063i05 (typical archives only)
- https://www.jstatsoft.org/article/view/v063c01 (code snippet with only replication code)
- https://www.jstatsoft.org/article/view/v063i02 (three files!)

**Comment by willpearse** [comment]
See #2 - let's bump this one to the head of the queue, then
