### ISSUE TITLE
Failed to download by install.packages("suppdata")

### ISSUE THREAD

**Issue by CidaJiang** [ropensci/suppdata#46]
Warning in install.packages :
  installation of package ‘rcrossref’ had non-zero exit status
Warning in install.packages :
  installation of package ‘suppdata’ had non-zero exit status

Sir, how to solve the problem?

**Comment by nuest** [comment]
Hi @CidaJiang ! Please provide the full output. `rcrossref` is required by `suppdata`, so you can try to install the former first:

```r
install.packages("rcrossref")
```

**Comment by CidaJiang** [comment]
Sir, I dried, but I failed.
the full output is following:

installing the source package ‘rcrossref’

试开URL’https://cran.rstudio.com/src/contrib/rcrossref_0.9.2.tar.gz'
Content type 'application/x-gzip' length 3260347 bytes (3.1 MB)
==================================================
downloaded 3.1 MB

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
  unknown timezone 'zone/tz/2019a.1.0/zoneinfo/Asia/Shanghai'
* installing *source* package ‘rcrossref’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace ‘rlang’ 0.2.0 is being loaded, but >= 0.3.0 is required
ERROR: lazy loading failed for package ‘rcrossref’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcrossref’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcrossref’
Warning in install.packages :
  installation of package ‘rcrossref’ had non-zero exit status
The downloaded source packages are in	‘/private/var/folders/gq/5m00r_qd3l72v0gstdn24rvw0000gn/T/Rtmpcgd4ce/downloaded_packages’

**Comment by CidaJiang** [comment]
Sir, I dried, but I failed.
the full output is following:

installing the source package ‘rcrossref’

Try to open URL’https://cran.rstudio.com/src/contrib/rcrossref_0.9.2.tar.gz'
Content type 'application/x-gzip' length 3260347 bytes (3.1 MB)
downloaded 3.1 MB

Warning in strptime(xx, f <- "%Y-%m-%d %H:%M:%OS", tz = tz) :
unknown timezone 'zone/tz/2019a.1.0/zoneinfo/Asia/Shanghai'

installing source package ‘rcrossref’ ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
namespace ‘rlang’ 0.2.0 is being loaded, but >= 0.3.0 is required
ERROR: lazy loading failed for package ‘rcrossref’
removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcrossref’
restoring previous ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rcrossref’
Warning in install.packages :
installation of package ‘rcrossref’ had non-zero exit status
The downloaded source packages are in ‘/private/var/folders/gq/5m00r_qd3l72v0gstdn24rvw0000gn/T/Rtmpcgd4ce/downloaded_packages’

**Comment by nuest** [comment]
The error message says your version of rlang is too old. Try running

update.packages()

**Comment by CidaJiang** [comment]
Thank you. 
I have updated my R. It's working now.

**Comment by willpearse** [comment]
No worries, and glad to hear it. Thanks for using the package and thank you
Daniel for being so helpful!

**Comment by nuest** [comment]
@CidaJiang if everything works, can you close the issue, please?
