### ISSUE TITLE
Ready for submission to ROpenSci / Journal of Open-Source Software?

### ISSUE THREAD

**Issue by willpearse** [ropensci/suppdata#7]
Is this ready to go? If it is, I'd like to bundle a journal submission in, as journal submission --> entry on tenure docket --> happy Will :D

@sckott

**Comment by sckott** [comment]
cool, I'll take a look

**Comment by sckott** [comment]
@willpearse looks okay to me. though I'm not sure xeno-canto is a good fit in the pkg. Are you pretty intent on including that?

**Comment by willpearse** [comment]
I'm not set on it; I'm just not sure what other package I would put it in,
and I prefer to have code up somewhere rather than not. If you think it's
better to remove it, it's gone.

Are you happy with the paper and with co-authorship? If so, once I hear
from you about Xeno-Canto I'll click the button.

**Comment by sckott** [comment]
Would it be easy enough to put xeno-canto in another pkg?  My preference would be to pull it out here, and put into another pkg. 

Otherwise, everything looks good. 

By click the button do you mean submit to ropensci review?

**Comment by willpearse** [comment]
I've removed Xeno-Canto from the package.

Yes, I do mean submit to ropensci review.

**Comment by sckott** [comment]
Okay, click away then.

**Comment by willpearse** [comment]
Will do! Click-y click-y time :D
