### ISSUE TITLE
You should clarify that this works with CrossRef DOIs only

### ISSUE THREAD

**Issue by rossmounce** [ropensci/suppdata#9]
CrossRef isn't the only game in town. Here's a fun non-CrossRef example:

```
> #mEDRA example, IOS Press, "The Clinical Evaluation of Parkinson’s Tremor" research article
> cr_agency(dois='10.3233/JPD-150650')
$DOI
[1] "10.3233/jpd-150650"

$agency
$agency$id
[1] "medra"

$agency$label
[1] "mEDRA"


> suppdata("10.3233/JPD-150650", 1)
Error in func(x, si, save.name = save.name, cache = cache, vol = vol,  : 
  EPMB download requires numeric SI info
```

**Comment by willpearse** [comment]
Is the entry in the help file sufficient for this? I say so there: https://github.com/willpearse/suppdata/blob/master/R/suppdata.R#L17

**Comment by rossmounce** [comment]
I was thinking of a mention upfront in the readme file, not many dig into code files (?)

**Comment by willpearse** [comment]
This is a link to the help-file for `suppdata`, in the part describing how it does the lookup.

At any rate, I'll put it in the readme; thanks for the suggestion.
